// You may write any gradle buildscript component in this file
// This file is automatically applied after build.gradle + dependencies.gradle is ran

// If you wish to use the default helper methods, uncomment the line below
// apply from: 'gradle/scripts/helpers.gradle'
spotless {
    java {
        // Don't forget to change the path.
        target 'src/*/java/me/desht/pneumaticcraft/**/*.java'

        leadingTabsToSpaces()
        endWithNewline()
        removeUnusedImports()
    }
}

tasks.register('apiJar', Jar) {
    duplicatesStrategy(DuplicatesStrategy.FAIL)
    archiveClassifier.set('api')
    from(sourceSets.api.output)
}

artifacts {
    archives apiJar
}
