// Date: 30-6-2015 15:38:53
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package me.desht.pneumaticcraft.client.model.entity;

import me.desht.pneumaticcraft.client.util.RenderUtils;
import me.desht.pneumaticcraft.common.entity.living.EntityDrone;
import me.desht.pneumaticcraft.common.minigun.Minigun;
import me.desht.pneumaticcraft.lib.Textures;
import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;

public class ModelDroneMinigun extends ModelBase {
    //fields
    private final ModelRenderer barrel;
    private final ModelRenderer support1;
    private final ModelRenderer support2;
    private final ModelRenderer support3;
    private final ModelRenderer support4;
    private final ModelRenderer support5;
    private final ModelRenderer main;
    private final ModelRenderer magazine;
    private final ModelRenderer mount;
    private final ModelRenderer magazineColor;

    public ModelDroneMinigun() {
        this.textureWidth = 64;
        this.textureHeight = 32;

        this.barrel = new ModelRenderer(this, 30, 15);
        this.barrel.addBox(-0.5F, 1.5F, 0F, 1, 1, 16);
        this.barrel.setRotationPoint(0F, 20.96667F, -8F);
        this.barrel.setTextureSize(64, 32);
        this.barrel.mirror = true;
        this.setRotation(this.barrel, 0F, 0F, 0F);
        this.support1 = new ModelRenderer(this, 0, 0);
        this.support1.addBox(-1.5F, -1.5F, 0F, 3, 3, 1);
        this.support1.setRotationPoint(0F, 21F, -6F);
        this.support1.setTextureSize(64, 32);
        this.support1.mirror = true;
        this.setRotation(this.support1, 0F, 0F, 0F);
        this.support2 = new ModelRenderer(this, 0, 4);
        this.support2.addBox(-1F, 1.5F, 0F, 2, 1, 1);
        this.support2.setRotationPoint(0F, 21F, -6F);
        this.support2.setTextureSize(64, 32);
        this.support2.mirror = true;
        this.setRotation(this.support2, 0F, 0F, 0F);
        this.support3 = new ModelRenderer(this, 0, 6);
        this.support3.addBox(-1F, -2.5F, 0F, 2, 1, 1);
        this.support3.setRotationPoint(0F, 21F, -6F);
        this.support3.setTextureSize(64, 32);
        this.support3.mirror = true;
        this.setRotation(this.support3, 0F, 0F, 0F);
        this.support4 = new ModelRenderer(this, 0, 8);
        this.support4.addBox(1.5F, -1F, 0F, 1, 2, 1);
        this.support4.setRotationPoint(0F, 21F, -6F);
        this.support4.setTextureSize(64, 32);
        this.support4.mirror = true;
        this.setRotation(this.support4, 0F, 0F, 0F);
        this.support5 = new ModelRenderer(this, 0, 11);
        this.support5.addBox(-2.5F, -1F, 0F, 1, 2, 1);
        this.support5.setRotationPoint(0F, 21F, -6F);
        this.support5.setTextureSize(64, 32);
        this.support5.mirror = true;
        this.setRotation(this.support5, 0F, 0F, 0F);
        this.main = new ModelRenderer(this, 36, 0);
        this.main.addBox(0F, 0F, 0F, 6, 6, 8);
        this.main.setRotationPoint(-3F, 18F, 8F);
        this.main.setTextureSize(64, 32);
        this.main.mirror = true;
        this.setRotation(this.main, 0F, 0F, 0F);
        this.magazine = new ModelRenderer(this, 0, 14);
        this.magazine.addBox(0F, 0F, 0F, 2, 3, 6);
        this.magazine.setRotationPoint(3F, 22F, 9F);
        this.magazine.setTextureSize(64, 32);
        this.magazine.mirror = true;
        this.setRotation(this.magazine, 0F, 0F, 0F);
        this.mount = new ModelRenderer(this, 0, 23);
        this.mount.addBox(0F, 0F, 0F, 2, 4, 2);
        this.mount.setRotationPoint(-1F, 15F, 11F);
        this.mount.setTextureSize(64, 32);
        this.mount.mirror = true;
        this.setRotation(this.mount, 0F, 0F, 0F);
        this.magazineColor = new ModelRenderer(this, 8, 0);
        this.magazineColor.addBox(0F, 0F, 0F, 1, 2, 4);
        this.magazineColor.setRotationPoint(4.3F, 22.5F, 10F);
        this.magazineColor.setTextureSize(64, 32);
        this.magazineColor.mirror = true;
        this.setRotation(this.magazineColor, 0F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        EntityDrone drone = (EntityDrone) entity;
        this.renderMinigun(drone != null ? drone.getMinigun() : null, f5, 0, true);
    }

    public void renderMinigun(Minigun minigun, float size, float partialTick, boolean renderMount) {
        Minecraft.getMinecraft().getTextureManager().bindTexture(Textures.MODEL_DRONE_MINIGUN);
        GlStateManager.color(1, 1, 1, 1);
        GlStateManager.pushMatrix();
        if (renderMount) {
            GlStateManager.translate(0, 5 / 16D, -12 / 16D);
            this.mount.render(size);
            GlStateManager.translate(0, -5 / 16D, 12 / 16D);
        }

        float barrelRotation = 0;
        if (minigun != null) {
            barrelRotation = (float) (minigun.getOldMinigunRotation() + partialTick * (minigun.getMinigunRotation() - minigun.getOldMinigunRotation()));
            double yaw = minigun.oldMinigunYaw + partialTick * (minigun.minigunYaw - minigun.oldMinigunYaw);
            double pitch = minigun.oldMinigunPitch + partialTick * (minigun.minigunPitch - minigun.oldMinigunPitch);

            GlStateManager.translate(0, 23 / 16D, 0);
            GlStateManager.rotate((float) yaw, 0, 1, 0);
            GlStateManager.rotate((float) pitch, 1, 0, 0);
            GlStateManager.translate(0, -18 / 16D, -12 / 16D);
        }
        this.barrel.rotateAngleY = 0;
        this.barrel.rotateAngleX = 0;
        for (int i = 0; i < 6; i++) {
            this.barrel.rotateAngleZ = (float) (Math.PI / 3 * i) + barrelRotation;
            this.barrel.render(size);
        }
        this.support1.rotateAngleZ = barrelRotation;
        this.support2.rotateAngleZ = barrelRotation;
        this.support3.rotateAngleZ = barrelRotation;
        this.support4.rotateAngleZ = barrelRotation;
        this.support5.rotateAngleZ = barrelRotation;
        this.support1.render(size);
        this.support2.render(size);
        this.support3.render(size);
        this.support4.render(size);
        this.support5.render(size);
        this.magazine.render(size);
        this.main.render(size);
        GlStateManager.disableTexture2D();
        RenderUtils.glColorHex(minigun != null ? 0xFF000000 | minigun.getAmmoColor() : 0xFF313131);
        this.magazineColor.render(size);
        GlStateManager.color(1, 1, 1, 1);
        GlStateManager.enableTexture2D();
        GlStateManager.popMatrix();
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

}
