plugins {
    id 'java'
    id 'maven-publish'
    id 'org.jetbrains.gradle.plugin.idea-ext' version '1.1.9'
    id 'com.gtnewhorizons.retrofuturagradle' version '1.4.1'
    id 'com.matthewprenger.cursegradle' version '1.4.0' apply false
    id 'com.modrinth.minotaur' version '2.+' apply false
    id 'org.jetbrains.changelog' version '2.2.1'
}

apply from: 'gradle/scripts/helpers.gradle'

// Project metadata configuration
version = "${mc_version}-${mod_version_massive}.${mod_version_major}.${mod_version_minor}"
group = "me.desht.pneumaticcraft"
archivesBaseName = "pneumaticcraft-repressurized"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
        vendor = JvmVendorSpec.AZUL
    }
    withSourcesJar()
}

minecraft {
    mcVersion = '1.12.2'
    mcpMappingChannel = 'stable'
    mcpMappingVersion = '39'
    username = 'Developer'

    extraRunJvmArguments.addAll([
            '-Dfml.coreMods.load=elucent.albedo.asm.FMLPlugin'
    ])
}

repositories {
    maven {
        name = "CleanroomMC Maven"
        url = "https://maven.cleanroommc.com"
    }
    maven {
        name = "CoFH Maven"
        url = "https://maven.covers1624.net"
    }
    maven {
        name = "JEI"
        url = "https://dvs1.progwml6.com/files/maven"
    }
    maven {
        name = "MCMP"
        url = "https://maven.amadornes.com/"
    }
    maven {
        name = "OpenComputers"
        url = "https://maven.cil.li/"
    }
    maven {
        name = "hwyla"
        url = 'https://tehnut.info/maven'
    }
    maven { // TOP
        name = "tterrag maven"
        url = "https://maven.tterrag.com/"
    }
    maven {
        name = 'BlameJared - Crafttweaker/Patchouli'
        url = 'https://maven.blamejared.com/'
    }
    maven {
        name = "K-4u Mod maven"
        url = "https://modmaven.k-4u.nl/"
    }
    maven {
        name = "Curseforge"
        url = "https://cursemaven.com"
    }
    maven { // Albedo Lights
        url = 'https://oldrepo.y2k.diy/'
    }
    maven { // Baubles
        name = "thiakil"
        url = "https://maven.thiakil.com/"
    }
}

dependencies {
    // Core dependencies
    implementation "cofh:RedstoneFlux:1.12-${redstone_flux_version}:universal"
    compileOnly "mezz.jei:jei_1.12.2:${jei_version}"
    compileOnly "cofh:CoFHCore:1.12.2-${cofhcore_version}:deobf"
    compileOnly "MCMultiPart2:MCMultiPart:${mcmultipart_version}"
    compileOnly "li.cil.oc:OpenComputers:MC1.12.2-${oc_version}:api"
    compileOnly "dan200.computercraft:ComputerCraft:${computercraft_version}"
    compileOnly "curse.maven:hwyla-253449:${hwyla_cfid}"
    compileOnly "mcjty.theoneprobe:TheOneProbe-1.12:${top_version}"
    compileOnly "CraftTweaker2:CraftTweaker2-API:${crafttweaker_version}"
    compileOnly "CraftTweaker2:CraftTweaker2-MC1120-Main:1.12-${crafttweaker_version}"
    compileOnly "net.industrial-craft:industrialcraft-2:2.8.27-ex112:api"
    compileOnly "thaumcraft:Thaumcraft:${thaumcraft_version}"
    compileOnly "team.chisel.ctm:CTM:${ctm_version}:api"
    compileOnly "vazkii.botania:Botania:${botania_version}"
    compileOnly("appeng:appliedenergistics2:${ae2_version}:api")
    compileOnly "vazkii.patchouli:Patchouli:${patchouli_version}"
    compileOnly "blusunrize:ImmersiveEngineering:${immersive_engineering_version}"
    compileOnly "com.azanor.baubles:Baubles:${baubles_version}"

    // Modern dependency resolution
    compileOnly "curse.maven:mekanism-268560:2835175" // Mekanism-1.12.2-9.8.3.390
    compileOnly "curse.maven:igw-mod-268495:2801979" // IGW-Mod-1.12.2-1.4.3-14
    compileOnly "curse.maven:albedo-301051:2806127" // albedo-2.0-SNAPSHOT
}

processResources {
    inputs.property "version", project.version
    filesMatching("mcmod.info") {
        expand 'version': project.version, 'mcversion': minecraft.mcVersion
    }
}

jar {
    manifest {
        attributes([
                "FMLAT": "pneumaticcraft_at.cfg",
                "FMLCorePlugin": "elucent.albedo.asm.FMLPlugin",
                "FMLCorePluginContainsFMLMod": "true"
        ])
    }

    from("LICENSE") {
        rename { "${it}_${archivesBaseName}" }
    }
}

idea {
    module {
        inheritOutputDirs = true
        downloadJavadoc = true
        downloadSources = true
    }
}

apply from: 'gradle/scripts/publishing.gradle'