package me.desht.pneumaticcraft.client.model.semiblocks;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelHeatFrame extends ModelBase {
    //fields
    final ModelRenderer Bottom3;
    final ModelRenderer Bottom4;
    final ModelRenderer Bottom5;
    final ModelRenderer Bottom6;
    final ModelRenderer Bottom7;
    final ModelRenderer Bottom8;
    final ModelRenderer Bottom2;
    final ModelRenderer Bottom1;
    final ModelRenderer Shape1;
    final ModelRenderer Shape2;
    final ModelRenderer Shape3;
    final ModelRenderer Shape4;
    final ModelRenderer Top6;
    final ModelRenderer Top3;
    final ModelRenderer Top4;
    final ModelRenderer Top8;
    final ModelRenderer Top1;
    final ModelRenderer Top5;
    final ModelRenderer Top2;
    final ModelRenderer Top7;

    public ModelHeatFrame() {
        this.textureWidth = 64;
        this.textureHeight = 64;

        this.Bottom3 = new ModelRenderer(this, 0, 0);
        this.Bottom3.addBox(0F, 0F, 0F, 4, 4, 4);
        this.Bottom3.setRotationPoint(-8.5F, 20.5F, 4.5F);
        this.Bottom3.setTextureSize(64, 64);
        this.Bottom3.mirror = true;
        this.setRotation(this.Bottom3, 0F, 0F, 0F);
        this.Bottom4 = new ModelRenderer(this, 16, 0);
        this.Bottom4.addBox(0F, 0F, 0F, 4, 4, 4);
        this.Bottom4.setRotationPoint(4.5F, 20.5F, 4.5F);
        this.Bottom4.setTextureSize(64, 64);
        this.Bottom4.mirror = true;
        this.setRotation(this.Bottom4, 0F, 0F, 0F);
        this.Bottom5 = new ModelRenderer(this, 32, 0);
        this.Bottom5.addBox(0F, 0F, 0F, 9, 1, 1);
        this.Bottom5.setRotationPoint(-4.5F, 23.5F, -8.5F);
        this.Bottom5.setTextureSize(64, 64);
        this.Bottom5.mirror = true;
        this.setRotation(this.Bottom5, 0F, 0F, 0F);
        this.Bottom6 = new ModelRenderer(this, 32, 2);
        this.Bottom6.addBox(0F, 0F, 0F, 9, 1, 1);
        this.Bottom6.setRotationPoint(-4.5F, 23.5F, 7.5F);
        this.Bottom6.setTextureSize(64, 64);
        this.Bottom6.mirror = true;
        this.setRotation(this.Bottom6, 0F, 0F, 0F);
        this.Bottom7 = new ModelRenderer(this, 44, 0);
        this.Bottom7.addBox(0F, 0F, 0F, 1, 1, 9);
        this.Bottom7.setRotationPoint(-8.5F, 23.5F, -4.5F);
        this.Bottom7.setTextureSize(64, 64);
        this.Bottom7.mirror = true;
        this.setRotation(this.Bottom7, 0F, 0F, 0F);
        this.Bottom8 = new ModelRenderer(this, 32, 4);
        this.Bottom8.addBox(0F, 0F, 0F, 1, 1, 9);
        this.Bottom8.setRotationPoint(7.5F, 23.5F, -4.5F);
        this.Bottom8.setTextureSize(64, 64);
        this.Bottom8.mirror = true;
        this.setRotation(this.Bottom8, 0F, 0F, 0F);
        this.Bottom2 = new ModelRenderer(this, 0, 8);
        this.Bottom2.addBox(0F, 0F, 0F, 4, 4, 4);
        this.Bottom2.setRotationPoint(-8.5F, 20.5F, -8.5F);
        this.Bottom2.setTextureSize(64, 64);
        this.Bottom2.mirror = true;
        this.setRotation(this.Bottom2, 0F, 0F, 0F);
        this.Bottom1 = new ModelRenderer(this, 16, 8);
        this.Bottom1.addBox(0F, 0F, 0F, 4, 4, 4);
        this.Bottom1.setRotationPoint(4.5F, 20.5F, -8.5F);
        this.Bottom1.setTextureSize(64, 64);
        this.Bottom1.mirror = true;
        this.setRotation(this.Bottom1, 0F, 0F, 0F);
        this.Shape1 = new ModelRenderer(this, 0, 16);
        this.Shape1.addBox(0F, 0F, 0F, 1, 9, 1);
        this.Shape1.setRotationPoint(-8.5F, 11.5F, -8.5F);
        this.Shape1.setTextureSize(64, 64);
        this.Shape1.mirror = true;
        this.setRotation(this.Shape1, 0F, 0F, 0F);
        this.Shape2 = new ModelRenderer(this, 4, 16);
        this.Shape2.addBox(0F, 0F, 0F, 1, 9, 1);
        this.Shape2.setRotationPoint(7.5F, 11.5F, -8.5F);
        this.Shape2.setTextureSize(64, 64);
        this.Shape2.mirror = true;
        this.setRotation(this.Shape2, 0F, 0F, 0F);
        this.Shape3 = new ModelRenderer(this, 0, 16);
        this.Shape3.addBox(0F, 0F, 0F, 1, 9, 1);
        this.Shape3.setRotationPoint(-8.5F, 11.5F, 7.5F);
        this.Shape3.setTextureSize(64, 64);
        this.Shape3.mirror = true;
        this.setRotation(this.Shape3, 0F, 0F, 0F);
        this.Shape4 = new ModelRenderer(this, 0, 16);
        this.Shape4.addBox(0F, 0F, 0F, 1, 9, 1);
        this.Shape4.setRotationPoint(7.5F, 11.5F, 7.5F);
        this.Shape4.setTextureSize(64, 64);
        this.Shape4.mirror = true;
        this.setRotation(this.Shape4, 0F, 0F, 0F);
        this.Top6 = new ModelRenderer(this, 32, 26);
        this.Top6.addBox(0F, 0F, 0F, 9, 1, 1);
        this.Top6.setRotationPoint(-4.5F, 7.5F, -8.5F);
        this.Top6.setTextureSize(64, 64);
        this.Top6.mirror = true;
        this.setRotation(this.Top6, 0F, 0F, 0F);
        this.Top3 = new ModelRenderer(this, 0, 34);
        this.Top3.addBox(0F, 0F, 0F, 4, 4, 4);
        this.Top3.setRotationPoint(-8.5F, 7.5F, -8.5F);
        this.Top3.setTextureSize(64, 64);
        this.Top3.mirror = true;
        this.setRotation(this.Top3, 0F, 0F, 0F);
        this.Top4 = new ModelRenderer(this, 16, 26);
        this.Top4.addBox(0F, 0F, 0F, 4, 4, 4);
        this.Top4.setRotationPoint(4.5F, 7.5F, 4.5F);
        this.Top4.setTextureSize(64, 64);
        this.Top4.mirror = true;
        this.setRotation(this.Top4, 0F, 0F, 0F);
        this.Top8 = new ModelRenderer(this, 32, 30);
        this.Top8.addBox(0F, 0F, 0F, 1, 1, 9);
        this.Top8.setRotationPoint(-8.5F, 7.5F, -4.5F);
        this.Top8.setTextureSize(64, 64);
        this.Top8.mirror = true;
        this.setRotation(this.Top8, 0F, 0F, 0F);
        this.Top1 = new ModelRenderer(this, 0, 26);
        this.Top1.addBox(0F, 0F, 0F, 4, 4, 4);
        this.Top1.setRotationPoint(-8.5F, 7.5F, 4.5F);
        this.Top1.setTextureSize(64, 64);
        this.Top1.mirror = true;
        this.setRotation(this.Top1, 0F, 0F, 0F);
        this.Top5 = new ModelRenderer(this, 32, 28);
        this.Top5.addBox(0F, 0F, 0F, 9, 1, 1);
        this.Top5.setRotationPoint(-4.5F, 7.5F, 7.5F);
        this.Top5.setTextureSize(64, 64);
        this.Top5.mirror = true;
        this.setRotation(this.Top5, 0F, 0F, 0F);
        this.Top2 = new ModelRenderer(this, 16, 34);
        this.Top2.addBox(0F, 0F, 0F, 4, 4, 4);
        this.Top2.setRotationPoint(4.5F, 7.5F, -8.5F);
        this.Top2.setTextureSize(64, 64);
        this.Top2.mirror = true;
        this.setRotation(this.Top2, 0F, 0F, 0F);
        this.Top7 = new ModelRenderer(this, 44, 26);
        this.Top7.addBox(0F, 0F, 0F, 1, 1, 9);
        this.Top7.setRotationPoint(7.5F, 7.5F, -4.5F);
        this.Top7.setTextureSize(64, 64);
        this.Top7.mirror = true;
        this.setRotation(this.Top7, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        this.Bottom3.render(f5);
        this.Bottom4.render(f5);
        this.Bottom5.render(f5);
        this.Bottom6.render(f5);
        this.Bottom7.render(f5);
        this.Bottom8.render(f5);
        this.Bottom2.render(f5);
        this.Bottom1.render(f5);
        this.Shape1.render(f5);
        this.Shape2.render(f5);
        this.Shape3.render(f5);
        this.Shape4.render(f5);
        this.Top6.render(f5);
        this.Top3.render(f5);
        this.Top4.render(f5);
        this.Top8.render(f5);
        this.Top1.render(f5);
        this.Top5.render(f5);
        this.Top2.render(f5);
        this.Top7.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
